name: Build Firmware

on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make cmake

      - name: Install bin2uf2
        run: |
          git clone --depth=1 https://github.com/ataradov/tools.git $HOME/tools
          cd $HOME/tools/bin2uf2
          make
          sudo cp bin2uf2 /usr/local/bin/

      - name: Set up Pico SDK
        run: |
          git clone --depth=1 https://github.com/raspberrypi/pico-sdk.git $HOME/pico-sdk
          echo "PICO_SDK_PATH=$HOME/pico-sdk" >> $GITHUB_ENV

      - name: Build firmware (CMake)
        run: |
          mkdir -p firmware/build
          cd firmware/build
          cmake -DPICO_SDK_PATH=$PICO_SDK_PATH ..
          make -j$(nproc)
        env:
          PICO_SDK_PATH: ${{ env.PICO_SDK_PATH }}

      - name: Build firmware (Makefile)
        run: |
          cd firmware/make
          make
        env:
          PICO_SDK_PATH: ${{ env.PICO_SDK_PATH }}

      - name: Copy UF2 to bin
        run: |
          mkdir -p bin
          cp firmware/build/UsbSnifferLite.elf.uf2 bin/UsbSnifferLite.uf2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UsbSnifferLite.uf2
          path: bin/UsbSnifferLite.uf2
