name: Firmware Build CI

on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware-build.yml'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake gcc-arm-none-eabi

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build firmware
        run: ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UsbSnifferLite
          path: |
            firmware/build/UsbSnifferLite.uf2
            firmware/build/UsbSnifferLite.hex
            firmware/build/UsbSnifferLite.bin
